Repository NOVA-MJU/MJS-FRONT, pull requests merged in 2025-08, with the labels that each got.

#53 [Feat] 명대방송국 메인페이지에 연동 및 디자인 변경 및 주말 식단 예외처리
  src/api/main/broadcast-api.ts
  src/components/molecules/mainpage/Meal/index.tsx
  src/components/molecules/user/LoginButtons/index.tsx
  src/components/organisms/sections/BroadcastSection.tsx
  src/components/organisms/sections/MealSection.tsx
  src/pages/main/index.tsx
  src/types/broadcast/broadcastInfo.ts
Labels: Feat

#64 <Feat> 로그아웃 기능 추가 및 라우터 추가
  src/components/organisms/ProfileComponent.tsx
  src/pages/admin/index.tsx
  src/store/useAuthStore.ts
Labels: Feat

#68 [Fix] navbar 내부 로그인,로그아웃 기능 추가 및 로그인 상태에 따른 게시판 보안기능 추가
  package-lock.json
  package.json
  src/components/atoms/Button/Button.type.ts
  src/components/atoms/Button/ButtonActiveStyleMap.ts
  src/components/molecules/user/LoginButtons/index.tsx
  src/components/organisms/Navbar.tsx
  src/main.tsx
  src/pages/Login/index.tsx
  src/pages/board/index.tsx
  src/pages/index.tsx
Labels: Fix

#72 <Style> [#70] 공지사항 페이지 모바일 반응형 UI 구현
  src/components/molecules/common/CategoryFilter/index.tsx
  src/components/organisms/DetailItem/idex.tsx
  src/pages/notice/index.tsx
Labels: enhancement

#77 <Feat> 회원가입 새 요구사항 반영(파일 압축, 토스트메시지 추가, 문구 수정)
  src/components/molecules/user/EmailFieldWithVerification/index.tsx
  src/components/molecules/user/ProfileUploader.tsx/index.tsx
  src/components/organisms/Register/index.tsx
  src/hooks/useRegister.ts
Labels: enhancement, Fix

#79 <Style> 마이페이지 전체 반응형 UI 추가
  src/components/atoms/Button/LabelButton.tsx
  src/components/atoms/ImageViewer/index.tsx
  src/components/molecules/MyListItem/index.tsx
  src/components/molecules/common/Pagination/index.tsx
  src/components/molecules/user/ActivityBox/index.tsx
  src/components/molecules/user/ProfileCard/index.tsx
  src/components/organisms/Edit/PersonalInfo.tsx
  src/components/organisms/Edit/RequiredInfo.tsx
  src/components/organisms/Mypage/ActivitiesSection/index.tsx
  src/components/organisms/Mypage/InfoSection/index.tsx
  src/components/organisms/Mypage/ProfileSection/index.tsx
  src/components/templates/MyViewLayout.tsx
  src/pages/mypage/edit.tsx
  src/pages/mypage/index.tsx
Labels: enhancement

#80 [Feat] 메인페이지, 명대방송 페이지 반응형 구현 + 명대방송 데이터 Fetching UX 성능 개선
  src/components/molecules/mainpage/Tab/index.tsx
  src/components/organisms/Header.tsx
  src/components/organisms/Navbar.tsx
  src/components/templates/LayoutForMain.tsx
  src/pages/broadcast/index.tsx
Labels: bug, Feat

#84 [Feat] 명대뉴스 상세 페이지 및 학식 상세 페이지 반응형 구현
  src/components/molecules/mainpage/Meal/index.tsx
  src/components/organisms/Navbar.tsx
  src/components/organisms/WeeklyMenuTable/index.tsx
  src/pages/menu/index.tsx
  src/pages/news/NewsCard.tsx
  src/pages/news/SkeletonCard.tsx
  src/pages/news/index.tsx
Labels: Feat

#91 <Feat> 메인페이지 내부 광고 캐러셀, 실시간 검색 순위(더미), 학사일정, HOT 게시판 컴포넌트 구현
  public/ad/ad1.jpg
  public/ad/ad2.jpg
  src/components/molecules/mainpage/AcademicSchedulePanel/index.tsx
  src/components/molecules/mainpage/Advertise/index.tsx
  src/components/molecules/mainpage/HotBoardList.tsx/index.tsx
  src/components/molecules/mainpage/RealTimeRank/index.tsx
  src/components/organisms/Navbar.tsx
  src/components/templates/LayoutForMain.tsx
Labels: Feat

#99 <Refactor> 1차 QA 수정사항 반영
  public/logo/MJS_darkLogo.svg
  public/logo/MJS_lightLogo.svg
  src/components/molecules/CalendarListItem/index.tsx
  src/components/molecules/mainpage/Meal/index.tsx
  src/components/organisms/Comment/index.tsx
  src/components/organisms/Edit/RequiredInfo.tsx
  src/components/organisms/Footer.tsx
  src/components/organisms/LoginForm/index.tsx
  src/components/organisms/Navbar.tsx
  src/components/organisms/sections/MealSection.tsx
  src/components/organisms/sections/NewsSection.tsx
  src/hooks/useRegister.ts
  src/main.tsx
  src/pages/admin/notice/detail/index.tsx
  src/pages/admin/notice/write/index.tsx
  src/pages/board/detail/index.tsx
  src/pages/mypage/edit.tsx
  src/pages/mypage/index.tsx
  src/pages/notice/index.tsx
Labels: Feat
