Repository NOVA-MJU/MJS-FRONT, pull requests merged in 2025-03, with the labels that each got.

#9 <Feat> 메인페이지 내 공지 크롤링 데이터 API 연동
  src/api/noticeApi.jsx
  src/components/TabComponent.jsx
  src/pages/MainPage.jsx
Labels: Feat

#16 <Feat> 식단 상세 페이지 설계 (일주일치 + 오늘 메뉴 하이라이트)
  package-lock.json
  package.json
  src/App.jsx
  src/api/apiClient.jsx
  src/api/mealApi.jsx
  src/components/MealPlan.jsx
  src/components/Navbar.jsx
  src/pages/meal/MealPage.jsx
Labels: Feat

#19 Feat. My page 디자인
  jsconfig.json
  package-lock.json
  package.json
  src/App.jsx
  src/api/apiClient.jsx
  src/api/authApi.jsx
  src/api/commentApi.jsx
  src/api/userApi.jsx
  src/components/Button.jsx
  src/components/Comment/CommentForm.jsx
  src/components/Comment/CommentItem.jsx
  src/components/Comment/index.jsx
  src/components/ScrollToTop.jsx
  src/context/AuthContext.jsx
  src/db/userInfo.json
  src/main.jsx
  src/pages/board/BoardDetailPage.jsx
  src/pages/profile/activity/index.jsx
  src/pages/profile/edit/index.jsx
  src/pages/profile/index.jsx
  src/pages/profile/inquery/index.jsx
  src/pages/profile/inquery/write/index.jsx
  src/pages/profile/withdrawal/index.jsx
  vite.config.js
Labels: Feat

#18 <Feat> News Detail Page 상세 설계
  src/App.jsx
  src/api/mealApi.jsx
  src/api/newsApi.jsx
  src/components/MyoungjiNews.jsx
  src/pages/news/NewsPage.jsx
Labels: Feat

#25 <Fix> 식단 상세 페이지 디자인 개선 및 로직 추가
  src/App.jsx
  src/components/ScrollToTop.jsx
  src/pages/meal/MealPage.jsx
Labels: Feat, Fix

#28 <Fix> 회원가입 시 이메일 검증 로직 변경
  src/hooks/useSignupForm.js
  src/pages/LoginPage.jsx
  src/pages/SignupPage.jsx
  src/util/verifyRegex.js
Labels: Fix
